name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Rodar os testes de API via Controller
      run: npm run test-rest-controller

    - name: Subir a API REST
      run: npm run start-rest &

    - name: Subir a API GraphQL
      run: npm run start-graphql &

    - name: Esperar a API estar Funcionando
      run: sleep 5

    - name: Criar .env
      run: |
        echo "BASE_URL_REST=${{ secrets.BASE_URL_REST }}" >> .env
        echo "BASE_URL_GRAPHQL=${{ secrets.BASE_URL_GRAPHQL }}" >> .env 

    - name: Rodar os testes External de API REST via HTTP
      run: npm run test-rest-external

    - name: Rodar os testes External de API GraphQL via HTTP
      run: npm run test-graphql-external
